version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - frisbee
    restart: unless-stopped

  frisbeefreakz:
    container_name: frisbeefreakz_container
    entrypoint: ["java","-jar","/opt/Patterns-and-Frameworks-Backend-0.0.1-SNAPSHOT.jar"]
    image: openjdk:15-jdk-buster
    volumes:
      - ./app:/opt
    ports:
      - "8080:8080"
      - "9999:9999"
    networks:
      - frisbee
    restart: unless-stopped

networks:
  frisbee:
    driver: bridge
